# Generated by Django 2.1.3 on 2018-12-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181205_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PublishDate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
