# Generated by Django 2.1.3 on 2018-12-05 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181205_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 5, 17, 48, 23, 703211, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
