# Generated by Django 2.1.3 on 2018-12-05 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20181205_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 17, 53, 58, 274955, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
