# Generated by Django 2.1.3 on 2018-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20181205_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
