# Generated by Django 2.1.3 on 2018-12-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='default_email',
        ),
    ]
