# Generated by Django 2.1.3 on 2018-12-16 02:35

from django.db import migrations, models
import portfolio.models.portfolio_model
import portfolio.models.slider_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to=portfolio.models.portfolio_model.upload_image_path)),
                ('git_link', models.URLField(blank=True, max_length=300, null=True)),
                ('web_link', models.URLField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_quote', models.CharField(blank=True, max_length=120, null=True)),
                ('slider', models.ImageField(blank=True, null=True, upload_to=portfolio.models.slider_model.upload_image_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=portfolio.models.slider_model.upload_file_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
