# Generated by Django 2.1.3 on 2018-12-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AyatModel',
            new_name='Ayat',
        ),
        migrations.RenameModel(
            old_name='ExperienceModel',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='FamiliarModel',
            new_name='Familiar',
        ),
        migrations.RenameModel(
            old_name='InterestModel',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='PortfolioModel',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='SliderModel',
            new_name='Slider',
        ),
    ]
