# Generated by Django 2.1.3 on 2018-12-16 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181216_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayat',
            name='verse',
            field=models.CharField(default=datetime.datetime(2018, 12, 16, 11, 44, 49, 395943, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayat',
            name='verse_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
